# App name & port
spring.application.name=shopsmart
server.port=8080
# H2 In-memory Database
spring.datasource.url=jdbc:h2:mem:shopsmartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Custom App Properties
app.order.max-cod-limit=50000
app.export.path=./exports/